version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lozinka
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"

  myapp:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - kafka
      - postgres
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=lozinka
      - DB_NAME=mydb
    command: >
      bash -c "alembic upgrade head && python main.py"