"""Initial migration

Revision ID: 2866faf98f67
Revises: 
Create Date: 2024-06-11 20:38:42.046105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2866faf98f67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinacije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.Column('opis', sa.String(length=255), nullable=True),
    sa.Column('klima', sa.String(length=255), nullable=True),
    sa.Column('jezik', sa.String(length=255), nullable=True),
    sa.Column('kultura', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smjestaji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.Column('vrsta_smjestaja', sa.String(length=255), nullable=True),
    sa.Column('cijena', sa.Integer(), nullable=True),
    sa.Column('broj_soba', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turisti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=255), nullable=True),
    sa.Column('prezime', sa.String(length=255), nullable=True),
    sa.Column('lozinka', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('putovanja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_polaska', sa.String(length=255), nullable=True),
    sa.Column('datum_povratka', sa.String(length=255), nullable=True),
    sa.Column('cijena', sa.Integer(), nullable=True),
    sa.Column('broj_slobodnih_mjesta', sa.Integer(), nullable=True),
    sa.Column('destinacija_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destinacija_id'], ['destinacije.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rezervacije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_rezervacije', sa.String(length=255), nullable=True),
    sa.Column('broj_putnika', sa.Integer(), nullable=True),
    sa.Column('turisti_id', sa.Integer(), nullable=False),
    sa.Column('putovanje_id', sa.Integer(), nullable=False),
    sa.Column('smjestaj_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['putovanje_id'], ['putovanja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['smjestaj_id'], ['smjestaji.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turisti_id'], ['turisti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rezervacije')
    op.drop_table('putovanja')
    op.drop_table('turisti')
    op.drop_table('smjestaji')
    op.drop_table('destinacije')
    # ### end Alembic commands ###